export const userLabels = [
  "React Miami 2024",
  "Commit Your Code 2024",
  "Commit Your Code 2025",
  "THAT WI 2024",
  "NYC Code and Coffee meetup",
  "PHP X NYC meetup",
  "Torc stream ft Pauline",
  "DSD Night of JavaScript",
  "React Summit 2025",
  "JSConf Hawaii 2024",
  "Next.js Conf 2025",
  "Women Who Code NYC Meetup",
  "Tech Leads Unplugged Stream",
  "Code & Chill SF Meetup",
  "Open Source North 2025",
  "The DevOps Exchange 2024",
  "Build With AI Online Stream",
  "Full Stack Europe 2024",
  "Coffee and Commits Boston Meetup",
  "Laravel Live NYC 2025",
  "Cloudflare Developer Week 2024",
  "Ship It Show Live Stream",
  "GraphQL Galaxy 2025",
  "Svelte Summit 2024",
  "TypeScript Tea Time Meetup",
  "Frontend Connect Chicago 2025",
  "CodeConf Remote 2025",
  "Product Engineering Unconference",
  "Modern Web Conf 2025",
  "React Native EU 2024",
  "TechTO Meetup Toronto",
  "Startup Devs NYC Meetup",
  "Serverless Summit 2025",
  "CodeCatalyst Online Stream",
  "Web Devs Connect 2025",
  "Python Pizza Global 2024",
  "AI Engineer World 2025",
  "Frontend Fest Amsterdam 2025",
  "Tech in Motion Boston Meetup",
  "NodeConf Remote 2025",
  "State of React 2025 Stream",
  "Open Source Fridays Stream",
  "Indie Hackers SF Meetup",
  "VueConf Toronto 2025",
  "NextLevel JS 2024",
  "Build the Future Summit 2025",
  "Women in Tech Global 2025",
  "Changelog Live Stream",
  "DevX Denver Meetup",
  "JSNation Live 2025",
  "Remote Stack Conf 2025",
  "Full Stack Nights NYC",
  "AI Builders Live",
  "Kubernetes Connect 2025",
  "DigitalOcean Deploy 2024",
  "PyCon Mini NYC 2025",
  "DevRelX Summit 2025",
  "TypeWorld 2025",
  "CSS Day 2025",
  "CoffeeOps Chicago Meetup",
  "Indie Dev Day 2025",
  "CodeLand 2025",
  "GraphQL Conf Europe 2025",
  "All Things Open 2025",
  "React Rally 2025",
  "Frontend Love 2025",
  "Women Who Code ATL Meetup",
  "DockerCon 2025",
  "HashiTalks Global 2025",
  "TechCrunch Dev Stream",
  "Async JS Meetup",
  "Open Source Camp 2025",
  "DevHub Live Stream",
  "Design+Code Summit 2025",
  "TechNova NYC Meetup",
  "Cloud Native Connect 2025",
  "AI Frontiers Stream",
  "Remote Dev Talks 2025",
  "Build Better Systems 2025",
];
